@echo off
for /f %%a in ('docker network inspect nat --format "{{(index .IPAM.Config 0).Gateway}}"') do set DOCKER_GATEWAY=%%a

echo %DOCKER_GATEWAY%
docker pull horzsolt/fakturowniaservice:latest

docker rm -f fakturowniaservice 2>nul

docker run -d ^
  --name fakturowniaservice ^
  --restart unless-stopped ^
  -e VIR_SQL_SERVER_NAME="%VIR_SQL_SERVER_NAME%" ^
  -e VIR_SQL_DATABASE="%VIR_SQL_DATABASE%" ^
  -e VIR_SQL_USER="%VIR_SQL_USER%" ^
  -e VIR_SQL_PASSWORD="%VIR_SQL_PASSWORD%" ^
  -e VIR_FAKTUR_CLIENT_API_URL_TEMPLATE="%VIR_FAKTUR_CLIENT_API_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_INVOICE_API_URL_TEMPLATE="%VIR_FAKTUR_INVOICE_API_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_INVOICE_DL_PATH=C:\app\pdf ^
  -e VIR_FAKTUR_INVOICE_PDF_URL_TEMPLATE="%VIR_FAKTUR_INVOICE_PDF_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_PAYMENT_API_URL_TEMPLATE="%VIR_FAKTUR_PAYMENT_API_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_PRODUCT_API_URL_TEMPLATE="%VIR_FAKTUR_PRODUCT_API_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_WAREHOUSEDOC_API_URL_TEMPLATE="%VIR_FAKTUR_WAREHOUSEDOC_API_URL_TEMPLATE%" ^
  -e VIR_FAKTUR_WAREHOUSES_API_URL_TEMPLATE="%VIR_FAKTUR_WAREHOUSES_API_URL_TEMPLATE%" ^
  -e VIR_PATIKAMAN_CSVURL="%VIR_PATIKAMAN_CSVURL%" ^
  -e VIR_PATIKAMAN_LOGINURL="%VIR_PATIKAMAN_LOGINURL%" ^
  -e VIR_PATIKAMAN_PWD="%VIR_PATIKAMAN_PWD%" ^
  -e VIR_PATIKAMAN_USERNAME="%VIR_PATIKAMAN_USERNAME%" ^
  -e VIR_TEST_MODE=FALSE ^
  -e TZ=Europe/Budapest ^
  -e OTEL_ENDPOINT=http://%DOCKER_GATEWAY%:4318 ^
  -v C:\VIR\Faktur\logs:C:\app\logs ^
  -v C:\VIR\Faktur\pdfs:C:\app\pdf ^
  horzsolt/fakturowniaservice:latest